---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: netpol-all
placementBindingDefaults:
  name: netpol-all
policyDefaults:
  placement:
    placementName: placement-netpol
  categories:
    - CM Configuration Management
  complianceType: "musthave"
  controls: 
    - CM-2 Baseline Configuration
  consolidateManifests: false
  disabled: false
  namespace: open-cluster-management-global-set
  pruneObjectBehavior: "DeleteAll"
  remediationAction: enforce
  severity: high
  standards:
    - NIST SP 800-53
  policyAnnotations: {"argocd.argoproj.io/compare-options": "IgnoreExtraneous"}
policies:
  - name: netpol-all
    namespaceSelector:
      include: ["*"]
      exclude: ["openshift*","kube-*","default"]
    manifests:
      - path: input/
        kustomizeOptions:
          enableAlphaPlugins: true
          enableHelm: true
